
env = Environment(PIC = '24FJ128GB206', 
                  CC = 'xc16-gcc', 
                  PROGSUFFIX = '.cof', 
                  CFLAGS = '-g -omf=coff -x c -mcpu=$PIC', 
                  LINKFLAGS = '-omf=coff -mcpu=$PIC -Wl,--script="app_p24FJ128GB206.gld"', 
                  CPPPATH = '../lib')
env.PrependENVPath('PATH', '/opt/microchip/xc16/v1.24/bin')
bin2hex = Builder(action = 'xc16-bin2hex $SOURCE -omf=coff',
                  suffix = 'hex', 
                  src_suffix = 'cof')
env.Append(BUILDERS = {'Hex' : bin2hex})
list = Builder(action = 'xc16-objdump -omf=coff -S -D $SOURCE > $TARGET', 
               suffix = 'lst', 
               src_suffix = 'cof')
env.Append(BUILDERS = {'List' : list})

# env.Program('score', ['score.c',
#                       '../lib/timer.c',
#                       '../lib/ui.c',
#                       '../lib/uart.c',
# 			'../lib/pin.c',
# 			'../lib/oc.c'])
# env.Hex('score')
# env.List('score')

# env.Program('motor_control', ['motor_control.c',
#                       '../lib/timer.c',
#                       '../lib/ui.c',
#                       '../lib/uart.c',
#       '../lib/pin.c',
#       '../lib/oc.c'])
# env.Hex('motor_control')
# env.List('motor_control')

# env.Program('servo_control', ['servo_control.c',
#                       '../lib/timer.c',
#                       '../lib/ui.c',
#                       '../lib/uart.c',
#       '../lib/pin.c',
#       '../lib/oc.c'])
# env.Hex('servo_control')
# env.List('servo_control')
# 

# env.Program('ps2_read', ['ps2_read.c',
#                       '../lib/timer.c',
#                       '../lib/ui.c',
#                       '../lib/uart.c',
#                       '../lib/keymap.h'
#       '../lib/pin.c',
#       '../lib/oc.c'])
# env.Hex('ps2_read')
# env.List('ps2_read')


env.Program('main', ['main.c',
                      '../lib/timer.c',
                      '../lib/ui.c',
                      '../lib/uart.c',
                      '../lib/keymap.h',
      '../lib/pin.c',
      '../lib/oc.c'])
env.Hex('main')
env.List('main')
